name: Patch RouterOS 6.x (Stable Only)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'RouterOS version (e.g. 6.47.9)'
        required: true
        default: '6.47.9'

jobs:
  patch:
    runs-on: ubuntu-latest
    env:
      MIKRO_NPK_SIGN_PUBLIC_KEY: ${{ secrets.MIKRO_NPK_SIGN_PUBLIC_KEY }}
      MIKRO_LICENSE_PUBLIC_KEY: ${{ secrets.MIKRO_LICENSE_PUBLIC_KEY }}
      CUSTOM_NPK_SIGN_PRIVATE_KEY: ${{ secrets.CUSTOM_NPK_SIGN_PRIVATE_KEY }}
      CUSTOM_NPK_SIGN_PUBLIC_KEY: ${{ secrets.CUSTOM_NPK_SIGN_PUBLIC_KEY }}
      CUSTOM_LICENSE_PRIVATE_KEY: ${{ secrets.CUSTOM_LICENSE_PRIVATE_KEY }}
      CUSTOM_LICENSE_PUBLIC_KEY: ${{ secrets.CUSTOM_LICENSE_PUBLIC_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install requirements
        run: |
          sudo apt-get update
          sudo apt-get install -y squashfs-tools

      - name: Create workspace
        run: |
          mkdir -p build downloads

      - name: Download routeros-mmips-${{ github.event.inputs.version }}.npk (stable)
        run: |
          curl -L -o downloads/routeros-mmips-${{ github.event.inputs.version }}.npk https://www.mikrotik-software.de/downloads/routeros/${{ github.event.inputs.version }}/stable/mmips/routeros-mmips-${{ github.event.inputs.version }}.npk

      - name: Patch NPK
        run: |
          python3 patch.py npk downloads/routeros-mmips-${{ github.event.inputs.version }}.npk -O build/routeros-mmips-${{ github.event.inputs.version }}-patched.npk

      - name: Zip patched package
        run: |
          cd build
          zip routeros-mmips-${{ github.event.inputs.version }}-patched.zip routeros-mmips-${{ github.event.inputs.version }}-patched.npk

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: routeros-mmips-${{ github.event.inputs.version }}-patched
          path: build/routeros-mmips-${{ github.event.inputs.version }}-patched.zip
